name: Build Terraform Provider

on:
  push:
    paths:
      - '/name-generator-provider/**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'




      - name: Tidy Go modules
        run: go mod tidy

      - name: Get version from tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=dev" >> $GITHUB_OUTPUT
          fi
        
      - name: Build Linux binary
        run: |
          go mod download
          go build -o terraform-provider-namegen

      - name: Build Windows binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o terraform-provider-namegen.exe

      - name: Zip Linux binary
        run: |
          zip terraform-provider-namegen_${{ steps.get_version.outputs.VERSION }}_linux_amd64.zip terraform-provider-namegen

      - name: Zip Windows binary
        run: |
          zip terraform-provider-namegen_${{ steps.get_version.outputs.VERSION }}_windows_amd64.zip terraform-provider-namegen.exe

      - name: Upload Linux zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-namegen_${{ steps.get_version.outputs.VERSION }}_linux_amd64.zip
          path: terraform-provider-namegen_${{ steps.get_version.outputs.VERSION }}_linux_amd64.zip

      - name: Upload Windows zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-namegen_${{ steps.get_version.outputs.VERSION }}_windows_amd64.zip
          path: terraform-provider-namegen_${{ steps.get_version.outputs.VERSION }}_windows_amd64.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            terraform-provider-namegen_${{ steps.get_version.outputs.VERSION }}_linux_amd64.zip
            terraform-provider-namegen_${{ steps.get_version.outputs.VERSION }}_windows_amd64.zip
          generate_release_notes: true