name: Build Terraform Provider

on:
  push:
    paths:
      - '/name-generator-provider/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'




      - name: Tidy Go modules
        run: go mod tidy
        
      - name: Build Linux binary
        run: |
          go mod download
          go build -o terraform-provider-namegen

      - name: Build Windows binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o terraform-provider-namegen.exe

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-namegen-linux
          path: terraform-provider-namegen

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-namegen-windows
          path: terraform-provider-namegen.exe